FROM python:latest

COPY products/app.py /app/
COPY products/products.sql /app/
COPY key.txt /app/

WORKDIR /app

RUN pip3 install flask requests

ENV FLASK_APP=app.py

CMD ["flask", "run", "--host=0.0.0.0"]